<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
<description></description>
<name>CompanionPlanSave</name>
<tag></tag>
<elementGuidId></elementGuidId>
<selectorCollection>
<entry>
<key>BASIC</key>
<value></value>
</entry>
</selectorCollection>
<selectorMethod>BASIC</selectorMethod>
<useRalativeImagePath>false</useRalativeImagePath>
<webElementProperties>
<isSelected>true</isSelected>
<matchCondition>equals</matchCondition>
<name>xpath</name>
<type>Main</type>
<value>//*[@id='container']/table[2]/tbody/tr/td[6]/form/table[4]/tbody/tr[1]/td/a[2]/span</value>
</webElementProperties>
</WebElementEntity>
