<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
<description></description>
<name>EligibiltySelection</name>
<tag></tag>
<elementGuidId></elementGuidId>
<selectorCollection>
<entry>
<key>BASIC</key>
<value></value>
</entry>
</selectorCollection>
<selectorMethod>BASIC</selectorMethod>
<useRalativeImagePath>false</useRalativeImagePath>
<webElementProperties>
<isSelected>true</isSelected>
<matchCondition>equals</matchCondition>
<name>xpath</name>
<type>Main</type>
<value>.//*[@id='container']/table[2]/tbody/tr/td[6]/table/tbody/tr[3]/td/table[1]/tbody/tr[1]/td/table/tbody/tr/td/table/tbody/tr[2]/td[2]/select</value>
</webElementProperties>
</WebElementEntity>
