<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
<description></description>
<name>SelectingCreditAnswer2</name>
<tag></tag>
<elementGuidId></elementGuidId>
<selectorCollection>
<entry>
<key>BASIC</key>
<value></value>
</entry>
</selectorCollection>
<selectorMethod>BASIC</selectorMethod>
<useRalativeImagePath>false</useRalativeImagePath>
<webElementProperties>
<isSelected>true</isSelected>
<matchCondition>equals</matchCondition>
<name>xpath</name>
<type>Main</type>
<value>//div/span[@class="answerText"]/span[contains(text(),'No')]/../../span[@class='styled-radio']</value>
</webElementProperties>
</WebElementEntity>
