<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
<description></description>
<name>ComparePlanChooseBtn</name>
<tag></tag>
<elementGuidId></elementGuidId>
<selectorCollection>
<entry>
<key>BASIC</key>
<value></value>
</entry>
</selectorCollection>
<selectorMethod>BASIC</selectorMethod>
<useRalativeImagePath>false</useRalativeImagePath>
<webElementProperties>
<isSelected>true</isSelected>
<matchCondition>equals</matchCondition>
<name>xpath</name>
<type>Main</type>
<value>//table[@id="contentTable"]/tbody[@id='planHeaderBody']/tr[3]/td[2]/div/a/span[1]</value>
</webElementProperties>
</WebElementEntity>
