<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
<description></description>
<name>DependentSSN1Confirmation</name>
<tag></tag>
<elementGuidId></elementGuidId>
<selectorCollection>
<entry>
<key>BASIC</key>
<value></value>
</entry>
</selectorCollection>
<selectorMethod>BASIC</selectorMethod>
<useRalativeImagePath>false</useRalativeImagePath>
<webElementProperties>
<isSelected>true</isSelected>
<matchCondition>equals</matchCondition>
<name>xpath</name>
<type>Main</type>
<value>//*[@name="content:view:1:addDependents:dependentForm:person:ssnConfirm:cssn:ssn1"]</value>
</webElementProperties>
</WebElementEntity>
