<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
<description></description>
<name>CountofTable</name>
<tag></tag>
<elementGuidId></elementGuidId>
<selectorCollection>
<entry>
<key>BASIC</key>
<value></value>
</entry>
</selectorCollection>
<selectorMethod>BASIC</selectorMethod>
<useRalativeImagePath>false</useRalativeImagePath>
<webElementProperties>
<isSelected>true</isSelected>
<matchCondition>equals</matchCondition>
<name>xpath</name>
<type>Main</type>
<value>//*[@id='ReplaceLifePlan']/div/div/form/div[@class='data-body']/table/tbody/tr</value>
</webElementProperties>
</WebElementEntity>
