<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
<description></description>
<name>SelectingTierThree</name>
<tag></tag>
<elementGuidId></elementGuidId>
<selectorCollection>
<entry>
<key>BASIC</key>
<value></value>
</entry>
</selectorCollection>
<selectorMethod>BASIC</selectorMethod>
<useRalativeImagePath>false</useRalativeImagePath>
<webElementProperties>
<isSelected>true</isSelected>
<matchCondition>equals</matchCondition>
<name>xpath</name>
<type>Main</type>
<value>.//*[@id='ReplaceLifePlan']/div[2]/div/form/div[2]/table/tbody/tr[3]/td[2]/input</value>
</webElementProperties>
</WebElementEntity>
