<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
<description></description>
<name>TerminateDependentMonth</name>
<tag></tag>
<elementGuidId></elementGuidId>
<selectorCollection>
<entry>
<key>BASIC</key>
<value></value>
</entry>
</selectorCollection>
<selectorMethod>BASIC</selectorMethod>
<useRalativeImagePath>false</useRalativeImagePath>
<webElementProperties>
<isSelected>true</isSelected>
<matchCondition>equals</matchCondition>
<name>xpath</name>
<type>Main</type>
<value>//*[@id='EditLifePlan']/div/div/form/div/table/tbody/tr/td/select[contains(@name,'.etMonth')]</value>
</webElementProperties>
</WebElementEntity>
