<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
<description></description>
<name>PPTFalseCondition</name>
<tag></tag>
<elementGuidId></elementGuidId>
<selectorCollection>
<entry>
<key>BASIC</key>
<value></value>
</entry>
</selectorCollection>
<selectorMethod>BASIC</selectorMethod>
<useRalativeImagePath>false</useRalativeImagePath>
<webElementProperties>
<isSelected>true</isSelected>
<matchCondition>equals</matchCondition>
<name>xpath</name>
<type>Main</type>
<value>//*[@id='container']/form/table[1]/tbody/tr/td[6]/table[3]/tbody/tr[4]/td[4]/a</value>
</webElementProperties>
</WebElementEntity>
