<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
<description></description>
<name>YearToUpdate</name>
<tag></tag>
<elementGuidId></elementGuidId>
<selectorCollection>
<entry>
<key>BASIC</key>
<value></value>
</entry>
</selectorCollection>
<selectorMethod>BASIC</selectorMethod>
<useRalativeImagePath>false</useRalativeImagePath>
<webElementProperties>
<isSelected>true</isSelected>
<matchCondition>equals</matchCondition>
<name>xpath</name>
<type>Main</type>
<value>//*[@id='acaLowCostWidget']/div[2]/form/div/div[2]/div/div[2]/div[2]</value>
</webElementProperties>
</WebElementEntity>
